# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['locallens_mcp_entrypoint.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'mcp',
        'mcp.server',
        'mcp.server.fastmcp',
        'httpx',
        'pydantic',
        'packaging',
        'anyio',
        'mcp_server',
        'mcp_server.claude_connector',
        'mcp_server.config',
        'mcp_server.license',
        'mcp_server.updater',
        'mcp_server.tools',
        'mcp_server.tools.status',
        'mcp_server.tools.queries',
        'mcp_server.tools.actions',
        'mcp_server.tools.pro_tools',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='locallens-mcp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
