import os
import sys
from pathlib import Path

def get_app_data_dir() -> Path:
    """Gets the application data directory used by LocalLens."""
    if sys.platform == 'win32':
        appdata_env = os.getenv('APPDATA')
        if not appdata_env:
            raise RuntimeError("APPDATA environment variable is not set on Windows.")
        return Path(appdata_env) / 'LocalLens'
    else: # For macOS and Linux
        return Path.home() / '.config' / 'LocalLens'

def get_locallens_url() -> str:
    """
    Reads the dynamic port exposed by LocalLens backend, or defaults to 8000.
    Evaluated dynamically per-request to avoid race conditions if LocalLens
    is launched after the MCP server.
    """
    port = 8000
    port_file = get_app_data_dir() / "port.txt"
    if port_file.exists():
        try:
            port = int(port_file.read_text().strip())
        except ValueError:
            pass
    return f"http://127.0.0.1:{port}"

def get_local_token() -> str:
    """
    Reads the local API token generated by the LocalLens backend on first launch.
    This token is required as the X-Local-Token header for all sensitive endpoints
    (persona, metadata-store, privacy, smart-albums).

    Returns an empty string if the token file doesn't exist yet (backend not run).
    """
    token_file = get_app_data_dir() / "local_api_token.txt"
    if token_file.exists():
        return token_file.read_text().strip()
    return ""

def get_auth_headers() -> dict:
    """
    Returns the headers dict to include on every sensitive API call.
    Use as: await client.get(url, headers=get_auth_headers())
    """
    token = get_local_token()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["X-Local-Token"] = token
    return headers
